//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_Detalle
    {
        public int Num_Factura { get; set; }
        public int Num_Linea { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal Total_Linea { get; set; }
    
        public virtual Factura_Encabezado Factura_Encabezado { get; set; }
        public virtual Tipo_Servicio_Producto Tipo_Servicio_Producto { get; set; }
    }
}
