//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_Encabezado
    {
        public int Num_Factura { get; set; }
        public System.DateTime Fecha_Factura { get; set; }
        public int Id_Cliente { get; set; }
        public decimal Total_Factura { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Factura_Detalle Factura_Detalle { get; set; }
    }
}
