//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo_Marca_Vehiculo
    {
        public Modelo_Marca_Vehiculo()
        {
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int Id_Modelo_Marca_Vehiculo { get; set; }
        public string Nombre { get; set; }
        public int Codigo { get; set; }
    
        public virtual Marca_Vehiculo Marca_Vehiculo { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
