//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Servicio_Producto
    {
        public Tipo_Servicio_Producto()
        {
            this.Factura_Detalle = new HashSet<Factura_Detalle>();
        }
    
        public int Id_Tipo_Servicio_Producto { get; set; }
        public string Nombre { get; set; }
        public int Codigo { get; set; }
        public Nullable<int> Precio { get; set; }
    
        public virtual ICollection<Factura_Detalle> Factura_Detalle { get; set; }
    }
}
