//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Vehiculo_Cliente = new HashSet<Vehiculo_Cliente>();
        }
    
        public int Id_Vehiculo { get; set; }
        public int Placa { get; set; }
        public string Marca { get; set; }
        public int Id_Tipo_Vehiculo { get; set; }
        public int Id_Modelo_Marca_Vehiculo { get; set; }
        public int Cant_Puertas { get; set; }
        public int Cant_Ruedas { get; set; }
        public int Anio_Fabricacion { get; set; }
    
        public virtual Modelo_Marca_Vehiculo Modelo_Marca_Vehiculo { get; set; }
        public virtual Tipo_Vehiculo Tipo_Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculo_Cliente> Vehiculo_Cliente { get; set; }
    }
}
